# Rakefile - builds parser from grammar
# also runs tests

file 'vish.kpeg.rb' => 'vish.kpeg' do
  sh 'kpeg -f vish.kpeg && (sleep 1; ruby -c vish.kpeg.rb)'
end

task :test do
  sh "./vepl -s tests/all_tests.vsh -e exit"
end

task :default => ['vish.kpeg.rb']
