# Rakefile - builds parser from grammar
# also runs tests

file 'vish.kpeg.rb' => 'vish.kpeg' do
  sh 'kpeg -f vish.kpeg && (sleep 1; ruby -c vish.kpeg.rb)'
end

task :test_rb do
  sh "ruby tests/all_tests.rb"
end

task :test_vsh do
  sh "./vepl -s tests/all_tests.vsh -e exit"
end



task :test => [:test_rb, :test_vsh]
task :default => ['vish.kpeg.rb']
