#!/usr/bin/env ruby
# vepl.rb - starts Vish REPL with options

# TODO: REMOVEME
require 'pry'
require 'optparse'
require_relative 'load_path'


options = {
  :start => [],
  :execute => [],
  :finish => []
}
oparse = OptionParser.new do |opt|
  opt.banner = 'vepl - Read, Eval, Print Loop for Vish shell for Viper editor'
  opt.separator ''
  opt.on('-n', '--no-start', 'Do not execute startup scripts') do
    options[:no_start] = true
  end
  opt.on('-l', '--log', 'Start logging to vish.log') do
    options[:log] = true
    options[:start] << 'logger -s; on &() { logger :_ }'
    options[:finish] << 'logger -e'
  end
  opt.on('-e script', '--execute script', String, 'Execute this command at startup') do |script|
    options[:execute] << script
  end
  opt.on('--finish script', String, 'Execute this set of scripts upon exit of session') do |script|
    options[:finish] << script
  end
  opt.separator ''
  opt.on('-h', '--help', 'Display this help and exit') do
    puts opt
    exit
  end
  opt.on('-v', '--version', 'Display version of Vish shell and exit') do
    puts 'Vish version'
    puts Vish::VERSION
    exit
  end
end
oparse.parse!


 # setup exit handlers

at_exit do
  options[:finish].reverse.each do |code|
    cblock = Visher.parse! code
    $vm.call cblock
  end
end


# start REPL
$vm = vepl(options, argv:ARGV)

