

AllCops:
  Include:
    - '**/Rakefile'
    - 'bin/viper'
  Exclude:
    - 'test/**/*'
    - 'lib/vish/**'

Style/Documentation:
  Enabled: false


# Since Little  Linter cannot really parse Ruby code
# Multi-line method calls cannot be aligned the way Rubocop likes them
Style/AlignParameters:
  Enabled: false
# where the above config gives an offense
#  Exclude:
#    'lib/bin/exec.rb'
