# key_mappings.rb - method key_mappings returns a hash of keys to syms
def key_mappings
    {
    "\u0011" => :ctrl_q,
    "\001" => :ctrl_a,
    "\005" => :ctrl_e,
    "\u0014" => :ctrl_t,
    "\002" => :ctrl_b,
    "\u0013" => :ctrl_s,
    "\003" => :ctrl_c,   
    "\u000F" => :ctrl_o,
  "\004" => :ctrl_d,
    "\b" => :ctrl_h,
# duplicated with tab key
    #"\t" => :ctrl_i,
    "\u0019" => :ctrl_y,
    "\n" => :ctrl_j,
    "\v" => :ctrl_k,
    "\f" => :ctrl_l,
    "\t" => :tab,
    "\u007F" => :backspace,
  "\033[A" => :up,
  "\033[B" => :down,
  "\033[C" => :right,
  "\033[D" => :left, 
  # punctuation
    ';' => :semicolon,
    ':' => :colon,
    '.' => :period,
    ',' => :comma,
    '?' => :question,
    '!' => :exclamation,
    '~' => :tilde,
    '`' => :accent,
    '@' => :at,
    '#' => :number,
   '$' => :dollar,
    '%' => :percent,
    '^' => :caret,
    '&' => :ampersand,
    '*' => :asterisk,
    '(' => :lparen,
    ')' => :rparen,
    '-' => :hyphen,
    '_' => :underline,
    '=' => :equals,
  '+' => :plus,
  '\\' => :backslash,
    '/' => :slash,
    '|' => :pipe,
   "'" => :apostrophe,
    '"' => :quote,
    '<' => :less,
    '>' => :greater,
    '[' => :lbracket,
    ']' => :rbracket,
    '{' => :lbrace,
    '}' => :rbrace
  }
end
