cd ":{vhome}/vshtest"
source vunit.vsh
source test_vish.vsh
source test_ast.vsh
source test_editor.vsh
source test_search.vsh
source test_bin.vsh
source test_node_commands.vsh
source test_function.vsh
source test_arity.vsh
source test_cond.vsh
source test_cat.vsh
source test_test.vsh
source test_path_expansion.vsh
source test_type.vsh
source test_defn.vsh
source test_cmdlet.vsh
source test_slice_of.vsh
source test_glob.vsh
source test_read.vsh
source test_dir_cmds.vsh
source test_test_executables.vsh
source test_buffer.vsh
